from .database import Database
from .sentence_transformer_embedder import SentenceTransformerEmbedder


def test_large_database():
    print("=== INITIALIZING EMBEDDER AND DATABASE ===")
    embedder = SentenceTransformerEmbedder()
    db = Database(embedder)

    print("OK – database created")

    # ---------------------------------------------------
    # INSERT MANY DOCUMENTS
    # ---------------------------------------------------
    print("\n=== INSERTING MULTIPLE DOCUMENTS ===")

    examples = [
        ("What is your name?", "My name is ChatGPT."),
        ("How much is 2+2?", "The answer is 4."),
        ("What is the capital of France?", "Paris is the capital of France."),
        ("Explain quantum mechanics in one sentence.",
         "Quantum mechanics describes physical properties at very small scales."),
        ("Who wrote The Hobbit?", "J.R.R. Tolkien wrote The Hobbit."),
        ("What is photosynthesis?",
         "Photosynthesis is the process by which plants convert light into energy."),
        ("How do airplanes fly?",
         "Airplanes fly due to lift generated by the wings."),
        ("What is AI?", "AI stands for artificial intelligence."),
        ("Define gravity",
         "Gravity is a force that attracts two bodies with mass."),
        ("What is the boiling point of water?",
         "Water boils at 100 degrees Celsius at sea level."),
    ]

    for q, a in examples:
        assert db.insert(q, a), f"Insert failed for: {q}"

    assert len(db.documents) == len(examples), "Document count mismatch"
    print("OK – many documents inserted successfully")

    # ---------------------------------------------------
    # SEMANTIC RETRIEVAL TESTS
    # ---------------------------------------------------
    print("\n=== SEMANTIC GET TESTS ===")

    queries = [
        ("How do plants make food?", "Photosynthesis"),
        ("Name the city that is France's capital.", "Paris"),
        ("Give me the sum of two plus two.", "4"),
        ("Tell me who created The Hobbit.", "Tolkien"),
        ("What force pulls objects toward Earth?", "Gravity"),
        ("What temperature does water boil at?", "100 degrees Celsius")
    ]

    for query, expected_keyword in queries:
        answer, dist = db.get(query)
        print(f"\nQuery: {query}")
        print(f"Returned Answer: {answer}")
        print(f"Distance: {dist}")

        assert expected_keyword.lower() in answer.lower(), \
            f"Expected keyword '{expected_keyword}' not found in answer '{answer}'"

    print("OK – semantic retrieval works")

    # ---------------------------------------------------
    # EMPTY QUERY TEST
    # ---------------------------------------------------
    print("\n=== EMPTY QUERY TEST ===")
    answer, dist = db.get("")
    assert isinstance(answer, str)
    assert isinstance(dist, float)
    print("OK – empty query handled")

    # ---------------------------------------------------
    # LONG DOCUMENT INSERTION
    # ---------------------------------------------------
    print("\n=== LARGE DOCUMENT INSERTION TEST ===")

    long_question = "Explain the entire theory of relativity."
    long_answer = (
        "The theory of relativity, developed by Albert Einstein, consists of "
        "special relativity and general relativity. Special relativity applies "
        "to objects moving at constant speeds, especially at speeds close to "
        "the speed of light. It introduces concepts such as time dilation and "
        "length contraction. General relativity extends these ideas to include "
        "gravity, describing it not as a force but as the curvature of spacetime."
    )

    assert db.insert(long_question, long_answer), "Failed to insert long document"
    print("OK – long document inserted")

    # ---------------------------------------------------
    # QUERY FOR LONG DOCUMENT
    # ---------------------------------------------------
    print("\n=== LARGE DOCUMENT QUERY TEST ===")
    answer, dist = db.get("Describe Einstein's theory about gravity.")
    print("Long answer returned:", answer[:100], "...")
    assert "Einstein" in answer or "gravity" in answer.lower()

    print("OK – long document retrieval works")

    print("\n=== ALL TESTS PASSED SUCCESSFULLY ===")


if __name__ == "__main__":
    test_large_database()
